### ISSUE TITLE
More solvers support

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#149]
Z3 is good and stable, but according to SMT-comp, it's a bit slow than other solvers, in my experience of using klee, z3 is usually the slowest compared to btor, stp, yices, because solver time dominate most SE time, maybe it's worth to pull upstream's support of other solvers in.

**Comment by vitalych** [comment]
We used  to have STP before replacing it with Z3. Here are the reasons for this:
- We had problems with STP for years. It was crashing in multi-core mode, after forking S2E processes. Z3 proved to be a lot more stable and also has an incremental mode.
- Z3 has an MIT license, which is perfect for us. STP depends on some GPLed components, so we can't use it because of that. In principle, we are open to integrate any MIT/BSD/LGPL solver. GPLed solvers can't be integrated directly and will have to be used as an external component/service.

**Comment by humeafo** [comment]
Got it, it seems the license issue is indeed a problem for the SMT-COMP benchmark winner solvers.
