### ISSUE TITLE
s2ecmd seed_get_file don't work in sp mode

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#177]
Because in s2e_sp mode s2e_make_concolic never make "seed_fork" var symbolic, the should_fork logic: https://github.com/S2E/guest-tools/blob/master/common/s2ecmd/s2ecmd.c#L345 won't work, does it make sense to support getting seed file in !should_fork mode? If so, I'd like to make a PR.

**Comment by vitalych** [comment]
Seed file definitely make sense in sp mode, they will just be concrete. Before making a PR, please wait that I merge mine in a day or so. I have completely refactored how seed files are handled.

The seed searcher and seed scheduler plugins would no longer make sense in sp mode. Instead, what you could have is a counter in the bootstrap file that would fetch seed files in a loop and run them on your workload.

**Comment by humeafo** [comment]
Ok.
I think sp mode can be more powerful than it currently is, the mp mode has some defects even no symbolic data is used(speed cost is high, I even observed memory increasing constantly etc). sp mode can reuse some plugins without modifications.
The seedSearcher/s2ecmd can be reused with some tweaks in sp mode. In order to reuse some plugins, maybe we need the CONFIG_SYMBEX_MP definition for plugins to make it auto sp mode aware.

Another related problem is that in sp mode I need several states(eg. two states), one aim is to reuse the existing multiprocess support in sp mode in order to make some work run faster, another aim is to avoid the problem that some testcases may crash, and the existing plugins will terminate the crashed testcase state(it's reasonable, because maybe no ideal way to recover in such cases), but now we can't fork using symvar mechanism or calling executor's fork function, and the clone function is protected, is there anyway to fork a state cleanly in sp mode? Or, must I implement a fork-like function is executor?

**Comment by vitalych** [comment]
I think it may be much simpler to just start another s2e instance from the host for now.
In theory, you could call S2E::fork() to create a new instance, it doesn't depend on symbolic execution.
However, you cannot clone execution states in anyway in that mode because all the infrastructure that allows redirecting read/writes to per-state storage is not available.

I think that the bulk of memory usage comes from copy-on-write: the longer a state runs, the bigger it grows. If the OS decides to zero out 1GB of RAM, the state will grow to at least 1GB. I think it might make sense to investigate the content of memory pages and implement some sort of deduplication (#175).

**Comment by humeafo** [comment]
I understood your points, thanks.
