### ISSUE TITLE
Concolic execution in order to reduce the long time of 'Waiting for analysis' status

### ISSUE THREAD

**Issue by caballomaldito** [S2E/s2e-env#210]
I have reviewed the documentation (http://s2e.systems/docs/src/Howtos/Concolic.html?highlight=concolic) in order to analyze my binary fastest, due after 12 hours the status is 'Waiting for analysis'

1. Can you provide an example about the custom instructions 's2e_make_concolic'?
2. Via the method "Using the s2e.so plugin", is there a customizable parameter to adjust the concolition in order to accelerate the analysis process?

Thank you very much

**Comment by vitalych** [comment]
Hi. Could you please explain which commands you used to start your analysis?
Things can get stuck for many reasons, among them:
- Program to test is misconfigured (e.g., it's blocking waiting for input, check debug.txt and enable graphics output for debugging)
- Constraints are too complex (check with `perf top`, reduce size of symbolic input)
S2E allows marking parts of input files symbolic. It's not in the main documentation yet, you can find more details here: https://github.com/S2E/guest-tools/blob/master/common/s2ecmd/symfile.cpp#L374
- There is path explosion (check hot spots with `s2e forkprofile`).

1. Re. s2e_make_concolic, there are examples in the documentation.
2. Perhaps an explanation of what you want to test would help figureing out the best options.

**Comment by vitalych** [comment]
You should put it into `bootstrap.sh`. Actually, the bootstrap file already has support for this, the difference is that it reads the symbolic ranges from a file instead of the environment variable. So basically, you would put your `1-2` into a file called `0-0.png.symranges`, assuming your seed file is called `0-0.png`. If there is no `.symranges` file, the whole seed will be made concolic, otherwise only the ranges specified will be made concolic.
