### ISSUE TITLE
Cannot get Linux binary tutorial to execute symbolically 

### ISSUE THREAD

**Issue by wangray** [S2E/s2e-env#29]
I'm following the instructions at https://github.com/S2E/docs/blob/master/src/Tutorials/Coreutils.rst 
but when I run launch-s2e.sh, the program terminates within seconds. 

```
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] LinuxMonitor: Module load not yet implemented
2 [State 0] BaseInstructions: Message from guest (0xb77907d1): S2E_SYM_ARGS is not set. All arguments will be concrete
```

I can't get it to recognize `S2E_SYM_ARGS` anywhere. Is this tutorial out of date?

**Comment by adrianherrera** [comment]
Hi @wangray,

You do not need `S2E_SYM_ARGS` for this tutorial, because `cat` generally works on files. Two things to check:

1. Did you specify the `@@` when you created the project?
2. Did you put `echo "Here is some text" > ${SYMB_FILE}` into the bootstrap script?

If you did not do (1) then you the `cat` command will have no input. If you do not do (2) then S2E will fork many, many states (I'm guessing this is not the problem if it terminated within seconds).

For reference `S2E_SYM_ARGS` is described in https://github.com/S2E/docs/blob/master/src/Howtos/s2e.so.rst

Regards,
Adrian

**Comment by wangray** [comment]
Yes, I did both of those things.

**Comment by adrianherrera** [comment]
Interesting. Could you please archive the project and send it to me (adrian.herrera@epfl.ch).

**Comment by adrianherrera** [comment]
Is this now working? If so, could you please close the issue.
