### ISSUE TITLE
Query about s2e

### ISSUE THREAD

**Issue by tashfia-r** [S2E/s2e-env#384]
I have rather a query than issue. In the s2e document, symbolic execution of linux binaries are shown. Are those binaries of entire linux kernel? How does it (s2e-env) differentiate between linux binary and bios binary? Why bios binary is not supported? I would be grateful if you could answer to these questions.

**Comment by vitalych** [comment]
It's better to discuss this on s2e-dev mailing list.
S2E itself has no problems with BIOS binaries. Symbolic execution will work just fine. But you will have to set them up yourself because s2e-env does not provide a user-friendly way of doing it (creating a project, setting up proper launch-s2e.sh and config files).
If you want to add support for BIOS, you can start here: https://github.com/S2E/s2e-env/blob/master/s2e_env/commands/new_project.py

**Comment by vitalych** [comment]
#310 #361
