### ISSUE TITLE
Question about range of the target

### ISSUE THREAD

**Issue by yapbuty** [S2E/s2e-env#419]
Hello, sir.

I'm trying to understand s2e, and I'm getting used to s2e by following the s2e documents.

My question is, is it possible to run s2e for the linux kernel binary? (e.g., vmlinux)

I want to focus on some variables in the linux kernel, so I want to make them symbolic with `s2e_make_symbolic()`.

I check this is definitely possible for the user-level binaries, but I don't know it is still possible for the linux kernel.

Thanks.

**Comment by vitalych** [comment]
You can use s2e_make_symbolic in the kernel like in user-space programs.
Have a look at these header files: https://github.com/S2E/s2e-linux-kernel/tree/master/include/s2e
This is part of the s2e-linux-kernel repository, which contains the kernel used on Linux images built by `s2e image_build`.

**Comment by yapbuty** [comment]
Thank you for your reply!
However, I'm still confused because I want to run s2e for other linux kernel.

What I'm doing until now is, I tried to make a `new_project` with 32-bit linux kernel binary as a target binary.
But, it didn't works well, so I'm not confident if it is right.

So, what I want to ask again is,

[1]
is it right to replace just the target binary? (from normal user-level binary to (custom) kernel binary)

[2]
if [1] is wrong, Do I have to make a customized linux kernel images, and make a new_project with `--no-target`?


Thanks, again.

**Comment by vitalych** [comment]
`s2e new_project` does not support kernels, only user-space apps.

You must build the kernel yourself and install it into the guest image. S2E currently supports kernel 4.9.3. You will need to import a new kernel into https://github.com/S2E/s2e-linux-kernel/ and modify https://github.com/S2E/guest-images in order to build an image with it. Don't forget to cherry-pick all the LinuxMonitor support into the new kernel (see commit history).

If possible, use systemtap to inject instrumentation on the fly. It will save a lot of time compared to rebuilding a new VM image for every small change (http://s2e.systems/docs/Tutorials/SystemTap/index.html).
