### ISSUE TITLE
Questions about MergingSearcher

### ISSUE THREAD

**Issue by jskim20210115** [S2E/s2e-env#434]
Dear S2E developers,

Hi, I'm trying to understand S2E and hope to use it in my project.
I've read about the MergingSearcher and I'm trying the example program (http://s2e.systems/docs/StateMerging.html#using-state-merging-in-s2e)

However when I try the example, I got the error messages like below:

 [State 0] MergingSearcher: MergingSearcher: starting merge group 1
5 [State 0] MergingSearcher: MergingSearcher: merging state
5 [State 0] MergingSearcher: MergingSearcher: starting merge group 2
5 [State 0] MergingSearcher: MergingSearcher: merging state
....
6 [State 1] MergingSearcher: MergingSearcher: state does not belong to a merge group
6 [State 1] MergingSearcher: MergingSearcher: state id already has group id 1
6 [State 1] MergingSearcher: MergingSearcher: merging state

Is it the correct and expected situation?

I thought the new state should be merged according to the documentation but it seems the merging is not working because the map is not containing the same group id as a key but the log said the group id is already existing in the state but the groupId has not set to 0.

It seems like the state exists and groupId is also set but it does not exist in m_mergePools.
The only situation that I can imagine is that the groupId key is removed from m_mergePools from the code here: https://github.com/S2E/s2e/blob/master/libs2eplugins/src/s2e/Plugins/Searchers/MergingSearcher.cpp

Why does this happen?, Why does the value in the map erased in the situation? and Why does the group Id exist?

Would you please help me to understand the situation and about the plugin?

Thank you very much.

Best Regards,
JS

**Comment by vitalych** [comment]
Hi! Unfortunately, I haven't really looked at state merging in seven years, so it may well be that the code doesn't work as expected.
See #291 and https://github.com/S2E/s2e/pull/26.
@gkso is working on it, so he might be able to help you out.

**Comment by jskim20210115** [comment]
Thanks for the reply! It seems he knows how to make the plugin works.
Let me wait for the reply.

**Comment by gkso** [comment]
Hi, @jskim20210115 
I think the problem here is you have to set MergingSearcher as the default searcher. 
The current default searcher in s2e-config.lua is MultiSearcher and CUPASearcher. You may remove them from s2e-config.lua, otherwise, you can register MergingSearcher to MultiSearcher like this:
https://github.com/S2E/s2e/blob/master/libs2eplugins/src/s2e/Plugins/Searchers/CUPASearcher.cpp#L108

Besides, there is another problem with state merging. In S2EExecutionState::merge(), it compares the CPUX86State of the two merging states.
https://github.com/S2E/s2e/blob/master/libs2ecore/src/S2EExecutionState.cpp#L455
https://github.com/S2E/s2e/blob/master/libs2ecore/src/S2EExecutionStateRegisters.cpp#L357
However, the _kvm_request_interrupt_window_, _kvm_irq_, and _return_address_ may be different. So my solution is to skip them in S2EExecutionStateRegisters::compareArchitecturalConcreteState():

```c++
int S2EExecutionStateRegisters::compareArchitecturalConcreteState(const S2EExecutionStateRegisters &other) {
    CPUX86State *a = getCpuState();
    CPUX86State *b = other.getCpuState();

    int ret = memcmp(&a->eip, &b->eip, CPU_OFFSET(return_address) - CPU_OFFSET(eip));
    if (ret) {
        return ret;
    }
    
    // return_address may be different in our case
    ret = memcmp(&a->segs, &b->segs, CPU_OFFSET(se_common_start) - CPU_OFFSET(segs));
    if (ret) {
        return ret;
    }

    // do not compare KVM interrupt variables
    ret = memcmp(&a->se_common_end, &b->se_common_end, CPU_OFFSET(kvm_request_interrupt_window) - CPU_OFFSET(se_common_end));
    if (ret) {
        return ret;
    }

    ret = memcmp(&a->apic_state, &b->apic_state, sizeof(CPUX86State) - CPU_OFFSET(apic_state));
    return ret;
}
```
Also, between mergeStart and mergeEnd, we want to disable interrupts in guest OS to avoid irrelavent states are modified by system. 
As far as I remember, the variable all_apic_interrupts_disabled is not being checked in libcpu.
So my version of execution_loop in libcpu/src/cpu-exec.c would be something look like this:

```c
static bool execution_loop(CPUArchState *env) {
    uintptr_t last_tb = 0;
    int last_tb_exit_code = 0;
    TranslationBlock *ltb = NULL;

    for (;;) {
        bool has_interrupt = false;
        if (!env->all_apic_interrupts_disabled) {
            if (process_interrupt_request(env)) {
                // Ensure that no TB jump will be modified as
                // the program flow was changed
                ltb = NULL;
                has_interrupt = true;
            }
        }

...

        if (!env->all_apic_interrupts_disabled) {
            if (env->kvm_request_interrupt_window && (env->mflags & IF_MASK)) {
                env->kvm_request_interrupt_window = 0;
                return true;
            }
        }
    }

    return false;
}
```

**Comment by jskim20210115** [comment]
Hi @gkso,

Thank you for the explanation.
I understood your points.
Let me try it and check the result.

Thank you very much.
