### ISSUE TITLE
Image Build Error

### ISSUE THREAD

**Issue by Stormys** [S2E/s2e-env#49]
I been trying to build any of linux s2e image using s2e image_build but all seem to fail unsuccessfully. 

```
cd /home/jtumina/s2e/images/.tmp-output/decree-cgc-cfe-i386/decree-cgc-cfe && mv config-i386 .config
/home/jtumina/s2e/source/guest-images//Linux/docker/run-docker.sh linux-build-i386 /home/jtumina/s2e/images/.tmp-output/decree-cgc-cfe-i386/decree-cgc-cfe /home/jtumina/s2e/source/guest-images//Linux/docker/make-kernel.sh /home/jtumina/s2e/source/s2e-linux-kernel/include 98323 98323
Working dir: /home/jtumina/s2e/images/.tmp-output/decree-cgc-cfe-i386/decree-cgc-cfe
/bin/bash: /home/jtumina/s2e/source/guest-images/Linux/docker/make-kernel.sh: No such file or directory
/home/jtumina/s2e/source/guest-images//Makefile.linux:150: recipe for target '/home/jtumina/s2e/images/.stamps/decree-cgc-cfe-i386' failed
make: *** [/home/jtumina/s2e/images/.stamps/decree-cgc-cfe-i386] Error 127
make: *** Waiting for unfinished jobs....
 ```

Yet, I checked and make-kernel.sh does exist in that directory. Why would it be unable find such file?

 I did see an earlier issue #30, who had a similar error and the response was either to try in their home directory or use `s2e image_build -d`. This is in my home directory and unfortunately -d option will not work for me as I am on a corporate network with required proxy servers that I am unable to seem to configure to be used with the google api call to download the image.

**Comment by adrianherrera** [comment]
Hey @Stormys,

Yeah, this is becoming a bit of a pain honestly. The "No such file or directory" message is actually coming from the Docker image, not your local machine. So there is something wrong with how the directories get shared between the host and the guest image. I think I'll put this text in a different colour or something, because I agree that it is very confusing.

As to what's causing the error, I have no idea. I spent the last week building images constantly and had no issues. Unfortunately I won't be able to test anything until next week, but I'll have a look at this issue ASAP because it does seem to be happening more often than not.

Sorry!!

~Adrian

**Comment by adrianherrera** [comment]
Hey @Stormys, did you get this working? I can't reproduce.

**Comment by Stormys** [comment]
Hey @adrianherrera 

Nope. I tried on two machines and both ran into the same error. They were both Ubuntu 16.04. (doubt that matters). Also tried to figure out the error, but I am no docker expert. In the end I resorted to using the image on the google drive but I hope someone else who reproduces this error is able to figure it out.

**Comment by vitalych** [comment]
@Stormys did you try to connect to the running docker container and check the mount points in there?

**Comment by Stormys** [comment]
Hey,

I have not had much time to look at S2E, but I have figured out this issue.

My $HOME variable is set to a symbolic link to my actual home directory. Which caused issues for docker to find the correct files. 

While this is fix, probably want a way not to rely on $HOME for run-docker.sh
