### ISSUE TITLE
Is the CGC example really working?

### ISSUE THREAD

**Issue by humeafo** [S2E/s2e-env#51]
I followed the https://github.com/S2E/docs/blob/master/src/Tutorials/CGC.rst and use the https://github.com/S2E/decree/blob/master/samples/CADET_00001 CGC binary as in the example tutorial, but only one state 0 is executing in one hour, obviously something got wrong, is it really working or the doc is outdated or codes broken?

**Comment by adrianherrera** [comment]
Hmm I tried the CADET_00001 CGC binary last week ago and it worked fine. I'll try again tomorrow.

Do you see POV files in s2e-last?

**Comment by humeafo** [comment]
No POV files found in s2e-last. The "s2e run CADET_00001" TUI showed that only one state running, zero states terminated in 60 minutes, The cgc_debian image is built about two weeks ago, I'll rebuild it and try a clean rebuilding of s2e.

**Comment by adrianherrera** [comment]
Ok. There were quite a few updates to the s2e-linux-kernel repo and the LinuxMonitor plugins recently.

You can run `s2e update` in your environment to update the S2E engine repos. You'll have to update the s2e-linux-kernel repo manually.

Then try and rebuild. Let me know how it goes!

**Comment by humeafo** [comment]
Unfortunately, after rebuild the source and cgc_ image, the example still not work, the TUI showed that number of states is 2, but then got stuck, no further progress seen, no POVs in s2e-last dir.

**Comment by adrianherrera** [comment]
Ok, weird. Can you please upload the debug log so I can see it.

**Comment by humeafo** [comment]
the s2e-last dir is attached:
[cadet_00001.gz](https://github.com/S2E/s2e-env/files/1248154/cadet_00001.gz)

**Comment by Stormys** [comment]
This sounds like it is hanging which I have a feeling it has to do with [S2E/docs/22](https://github.com/S2E/docs/issues/22)

**Comment by adrianherrera** [comment]
Hi @humeafo,

Thanks for posting that. Note that s2e-env provides a `s2e export_project` command that you can use to archive your project. Then others can use `s2e import_project` to add the project into their environment.

I don't think is related to https://github.com/S2E/docs/issues/22. When I look through debug.txt I cannot see any output from the DecreeMonitor plugin. When state 0 starts you should get a message like:

```
[State 0] DecreeMonitor: handleInit: page_offset=0xc0000000 task_struct.pid offset=320
```

Since you are not getting this message, I suspect your sources  are out of date.

Have you updated the s2e-linux-kernel sources so that you have the s2e kernel module that sends this message (https://github.com/S2E/s2e-linux-kernel/blob/master/decree-cgc-cfe/kernel/s2e/s2e.c)?

And have you updated the libs2eplugins sources so that the DecreeMonitor plugin handles this message from the Decree kernel (https://github.com/S2E/libs2eplugins/blob/master/src/s2e/Plugins/OSMonitors/Linux/DecreeMonitor.cpp#L843)?

I suggest doing an `rm -rf images/.tmp-output images/.stamps` to make sure that any image remnants are deleted. When you build S2E use `s2e build -r libs2e` to force a rebuild of libs2e (which includes the libs2eplugins code).

**Comment by humeafo** [comment]
I confirmed that the source is up to date and removed images/.tmp-out etc, rebuild the image, rebuild libs2e, but it still not works, I confirmed that the kernel is up to date in cgc-debian-vm.
There is indeed no handleInit message in debug.txt, is it possible that the kernel code has no chance to run at all when the snapshot is recovered?

**Comment by humeafo** [comment]
I've updated s2e-env, but I'll confirm this tomorrow.

**Comment by adrianherrera** [comment]
I checked bootstrap.sh from the archive that you uploaded, and the modprobe command is missing, probably because the project was created with an older version of s2e-env. Try adding the modprobe command and let me know how it goes!

**Comment by humeafo** [comment]
Hi, @adrianherrera you are absolutely right! It's my mistake not properly install the updated s2e-env, so older version of s2e-env is used.
Thanks for your patient help.

**Comment by adrianherrera** [comment]
No worries, not your fault at all :)
