### ISSUE TITLE
Arm support required

### ISSUE THREAD

**Issue by windcarp** [S2E/s2e-env#64]
Thanks for your work! The s2e official website said that

> S²E runs unmodified x86, x86-64, or ARM software stacks

I checked the s2e-env but didn't find arm support. Does or Will the project support ARM architecture? 

Thanks!

**Comment by adrianherrera** [comment]
Hi @windcarp,

Hmmmm, this is not really true for the new version of S2E. Unfortunately, the new version does not yet support the ARM architecture.

I did start porting ARM support across (see the `improvement/arm-support` branches across a few repos - e.g. https://github.com/S2E/libtcg/tree/improvement/arm-support), but other priorities have since surfaced and I'm not really able to commit much time to this in the near future.

Feel free to take what I've done and finish it off! I'm happy to answer questions where I can.

~Adrian

**Comment by windcarp** [comment]
The motivation for this question is that I am doing some analysis work of some arm binaries, and I think `s2e` is better for real programs than `angr` does.

I've got another question to ask about this complex system. In addition to the input files, I did not find how to symbolize the network data, e.g `read(), write()` syscalls which are widely used. Does or Will `s2e` support this feature?

And thank you for your reply!

**Comment by vitalych** [comment]
- You can create symbolic files in a ram disk, there is already support for that. You can have a look at the bootstrap.sh (https://github.com/S2E/s2e-env/blob/master/s2e_env/templates/bootstrap.sh#L43)
- For network, there is no support yet. A simple hack you could do is hook read() and write() calls from user space using LD_PRELOAD. You can tweak s2e.so for that. It will only work with dynamically linked binaries.

**Comment by windcarp** [comment]
That's nice, I'll try.

And thank you for your work again!

**Comment by valour01** [comment]
I am here to ask more questions on the ARM support of S2E. I noticed that S2E 2.0 doesn't support ARM. However, I really need to do some analysis on the ARM binaries. 

I tried the S2E 1.0. I am not sure whether you guys will give support or answer the questions related to S2E 1.0. I follow the documentation in the repo s2e-old and I come across many problems while compilation like below:

```
/home/jmh/Downloads/s2e-old/s2e/build/llvm-3.2.src.native/include/llvm/Support/AlignOf.h:96:1: error: 'alignas' attribute
      cannot be applied to types
LLVM_ALIGNEDCHARARRAY_TEMPLATE_ALIGNMENT(64);
```

I am using ubuntu 16.04 and gcc 5.4. It would be great if you guys could give me some system version and compiler version that ever compiled s2e 1.0 successfully. 

Besides, if you don't support s2e 1.0 anymore. Do you have any suggestions or ideas if I want to do concolic execution on ARM binaries. All the suggestions and comments are welcome.

**Comment by vitalych** [comment]
You could check the documentation of the old S2E, it should contain the Ubuntu version needed. I think 14.04 was the last one supported.

As for ARM binaries, you could perhaps convert them to LLVM using McSema and then run the result in KLEE (https://github.com/trailofbits/mcsema). If your program doesn't interact with the environment too much, that would be the best choice currently. Otherwise, you will have to add ARM support to S2E.
